version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 6
    rebase-strategy: auto
    labels:
      - dependencies
    groups:
      production-patch-and-minor:
        dependency-type: production
        update-types:
          - patch
          - minor
      development-patch-and-minor:
        dependency-type: development
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/New_York
    open-pull-requests-limit: 3
    rebase-strategy: auto
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"
