param(
  [ValidateSet('menu','status','uptime','start','stop','restart','install-service','remove-service','migrate-service','setup','production-repair','db-test','migrate','dependency-test','dependency-install','port','logs','health','check-update','update','rollback','version','doctor','help')]
  [string]$Action='menu', [string]$Value=''
)
$ErrorActionPreference='Stop'
$Root=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$M=Get-Content -Raw (Join-Path $Root 'project-control.json')|ConvertFrom-Json
$State=Join-Path $Root 'runtime\project-control\state.json'
function Fail($m){Write-Host "ERROR: $m" -ForegroundColor Red;exit 1}
function Admin{$i=[Security.Principal.WindowsIdentity]::GetCurrent();$p=New-Object Security.Principal.WindowsPrincipal($i);$p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function NeedAdmin{if(-not(Admin)){Fail 'Run Project Control from an Administrator terminal.'}}
function Service{Get-Service -Name $M.serviceId -ErrorAction SilentlyContinue}
function Port{$p=[int]$M.defaultPort;$e=Join-Path $Root '.env';if(Test-Path $e){$l=Get-Content $e|?{$_ -match '^\s*PORT\s*=\s*(\d+)'}|select -Last 1;if($l -match '(\d+)'){$p=[int]$Matches[1]}};$p}
function Health{try{Invoke-RestMethod "http://127.0.0.1:$(Port)$($M.healthPath)" -TimeoutSec 8}catch{$null}}
function Listener{$p=Port;Get-NetTCPConnection -State Listen -LocalPort $p -ErrorAction SilentlyContinue|select -First 1}
function Status{$s=Service;$h=Health;$l=Listener;Write-Host "Project          : $($M.project)";Write-Host "Installed version: $((Get-Content -Raw (Join-Path $Root 'package.json')|ConvertFrom-Json).version)";Write-Host "Service          : $($M.serviceName)";Write-Host "Service ID       : $($M.serviceId)";Write-Host "Service state    : $(if($s){$s.Status}else{'not installed'})";Write-Host "Health           : $(if($h){'ok'}else{'unreachable'})";if($h){Write-Host "PID              : $($h.pid)";Write-Host "Uptime           : $([TimeSpan]::FromMilliseconds($h.uptimeMs))"};Write-Host "HTTP port        : $(Port)";Write-Host "Listener         : $(if($l){"LISTENING (PID $($l.OwningProcess))"}else{'not listening'})"}
function StopRuntime{$s=Service;if($s){NeedAdmin};if($s -and $s.Status-ne'Stopped'){Stop-Service $M.serviceId -Force};Start-Sleep 2;$h=Health;if($h){$l=Listener;if(-not$l -or [int]$l.OwningProcess-ne[int]$h.pid){Fail 'Health PID does not own the configured port.'};Stop-Process -Id ([int]$h.pid) -Force;Start-Sleep 2};if(Health){Fail 'RX Tracker still answers after stop.'};Status}
function StartRuntime{NeedAdmin;$s=Service;if(-not$s){Fail '0-RX-TRACKER is not installed.'};if($s.Status-ne'Running'){Start-Service $M.serviceId};$d=(Get-Date).AddSeconds(30);do{Start-Sleep 1;$h=Health}while(-not$h-and(Get-Date)-lt$d);if(-not$h){Fail 'RX Tracker did not become healthy.'};Status}
function RestartRuntime{StopRuntime;StartRuntime}
function Install{NeedAdmin;if(Service){Write-Host '0-RX-TRACKER is already installed.';return};& node (Join-Path $Root 'scripts\windows-service.js') install;if($LASTEXITCODE){exit $LASTEXITCODE};return}
function Remove{NeedAdmin;StopRuntime;& node (Join-Path $Root 'scripts\windows-service.js') uninstall;if($LASTEXITCODE){exit $LASTEXITCODE};return}
function SetPort{if(-not$Value){Write-Host "RX Tracker HTTP port: $(Port)";return};$n=0;if(-not[int]::TryParse($Value,[ref]$n)-or$n-lt1-or$n-gt65535){Fail 'Port must be 1-65535.'};$e=Join-Path $Root '.env';if(-not(Test-Path $e)){Fail '.env does not exist.'};Copy-Item $e "$e.project-control-backup" -Force;$lines=@(Get-Content $e);$found=$false;$lines=@($lines|%{if($_-match'^\s*PORT\s*='){$found=$true;"PORT=$n"}else{$_}});if(-not$found){$lines+="PORT=$n"};Set-Content $e $lines -Encoding UTF8;Write-Host "Port set to $n; restart to apply."}
function CheckUpdate{& git -C $Root fetch --tags --prune origin;if($LASTEXITCODE){Fail 'Git fetch failed.'};$t=& git -C $Root tag --list $M.releaseTagPattern --merged origin/main --sort=-version:refname|select -First 1;$c=& git -C $Root describe --tags --exact-match HEAD 2>$null;Write-Host "Current: $(if($c){$c}else{& git -C $Root rev-parse --short HEAD})";Write-Host "Latest : $t"}
function Clean{if(@(& git -C $Root status --porcelain).Count){Fail 'Checkout has uncommitted changes.'}}
function Update{Clean;CheckUpdate;$tag=& git -C $Root tag --list $M.releaseTagPattern --merged origin/main --sort=-version:refname|select -First 1;if(-not$tag){Fail 'No release tag found.'};New-Item -ItemType Directory (Split-Path $State) -Force|Out-Null;@{previous=(& git -C $Root rev-parse HEAD);target=$tag}|ConvertTo-Json|Set-Content $State;& git -C $Root checkout --detach $tag;if($LASTEXITCODE){exit $LASTEXITCODE};& npm ci;if($LASTEXITCODE){exit $LASTEXITCODE};& npm run db:migrate;if($LASTEXITCODE){exit $LASTEXITCODE};& npm run db:test;if($LASTEXITCODE){exit $LASTEXITCODE};if(Service){RestartRuntime}else{Write-Host 'Release installed; install the service to run it.' -ForegroundColor Yellow}}
function Rollback{Clean;if(-not(Test-Path $State)){Fail 'No rollback state.'};$x=Get-Content -Raw $State|ConvertFrom-Json;& git -C $Root checkout --detach $x.previous;if($LASTEXITCODE){exit $LASTEXITCODE};& npm ci;if(Service){RestartRuntime}}
function Doctor{foreach($c in 'git','node','npm','powershell.exe'){if(Get-Command $c -ErrorAction SilentlyContinue){Write-Host "[OK] $c" -ForegroundColor Green}else{Fail "$c missing"}};& npm run db:test;if($LASTEXITCODE){exit $LASTEXITCODE}}
function Setup{if(-not(Test-Path '.env')){Copy-Item '.env.example' '.env';Write-Host 'Created .env; configure it before starting.'};& npm ci;if($LASTEXITCODE){exit $LASTEXITCODE}}
function ProductionRepair{Setup;& npm run db:migrate;if($LASTEXITCODE){exit $LASTEXITCODE};Doctor;if(Service){RestartRuntime}}
function DbTest{& npm run db:test;exit $LASTEXITCODE}
function DependencyTest{& npm audit --omit=dev;exit $LASTEXITCODE}
function MigrateService{NeedAdmin;$pm2=Get-Command pm2 -ErrorAction SilentlyContinue;if($pm2){& pm2 delete patient-rx-system 2>$null|Out-Null;& pm2 save 2>$null|Out-Null};if(Service){Write-Host '0-RX-TRACKER is already installed; repairing wrapper registration.';StopRuntime;& node 'scripts/windows-service.js' uninstall;Start-Sleep 2;& node 'scripts/windows-service.js' install;StartRuntime;return};$h=Health;if($h){StopRuntime};Install;StartRuntime}
function Logs{$d=Join-Path $Root $M.logDirectory;$f=Get-ChildItem $d -File -ErrorAction SilentlyContinue|sort LastWriteTime -Descending|select -First 1;if(-not$f){Fail 'No logs found.'};Get-Content $f.FullName -Tail 100}
function Confirm($q){(Read-Host "$q Enter Y or YES").Trim()-match'^(?i:y|yes)$'}
function Run($a,$v=''){$args=@('-NoProfile','-ExecutionPolicy','Bypass','-File',$PSCommandPath,'-Action',$a);if($v){$args+=@('-Value',$v)};& powershell.exe @args;Write-Host "`nExit code: $LASTEXITCODE"}
function Menu{while($true){Clear-Host;Write-Host '================ RX TRACKER PROJECT CONTROL ================' -ForegroundColor Cyan;Write-Host ' INFORMATION';Write-Host '  1. Status                    2. Uptime';Write-Host '  3. Health details            4. Version information';Write-Host '  5. View logs                 6. Run doctor/validation';Write-Host '  7. Show configured ports     8. Check for release update';Write-Host '';Write-Host ' RUNTIME CONTROL';Write-Host '  9. Start                    10. Stop';Write-Host ' 11. Restart                  12. Install service/runtime';Write-Host ' 13. Remove service/runtime';Write-Host '';Write-Host ' CONFIGURATION AND RELEASES';Write-Host ' 14. Change ports             15. Install latest release';Write-Host ' 16. Roll back release        17. Command help';Write-Host ' 18. Migrate legacy manager';Write-Host '';Write-Host ' SETUP AND DEPENDENCIES';Write-Host ' 19. Project setup            20. Production setup/repair';Write-Host ' 21. Test database/storage    22. Run migrations';Write-Host ' 23. Test dependencies        24. Install/repair dependencies';Write-Host '';Write-Host '  0. Exit';$c=(Read-Host 'Select a menu number').Trim();switch($c){'0'{return};'1'{Run status};'2'{Run uptime};'3'{Run health};'4'{Run version};'5'{Run logs};'6'{Run doctor};'7'{Run port};'8'{Run check-update};'9'{Run start};'10'{if(Confirm 'Stop RX Tracker?'){Run stop}};'11'{if(Confirm 'Restart RX Tracker?'){Run restart}};'12'{if(Confirm 'Install 0-RX-TRACKER?'){Run install-service}};'13'{if(Confirm 'Remove 0-RX-TRACKER?'){Run remove-service}};'14'{$p=Read-Host 'New HTTP port';Run port $p};'15'{if(Confirm 'Install latest tagged release?'){Run update}};'16'{if(Confirm 'Rollback release?'){Run rollback}};'17'{Run help};'18'{if(Confirm 'Migrate or repair the RX Tracker manager?'){Run migrate-service}};'19'{if(Confirm 'Run project setup?'){Run setup}};'20'{if(Confirm 'Run production setup/repair?'){Run production-repair}};'21'{Run db-test};'22'{if(Confirm 'Run database migrations?'){Run migrate}};'23'{Run dependency-test};'24'{if(Confirm 'Install exact dependencies?'){Run dependency-install}};default{Write-Host 'Invalid selection'}};Read-Host 'Press Enter to return to the menu'|Out-Null}}
Set-Location $Root
switch($Action){menu{Menu};status{Status};uptime{$h=Health;if(-not$h){Fail 'Unreachable'};[TimeSpan]::FromMilliseconds($h.uptimeMs)};start{StartRuntime};stop{StopRuntime};restart{RestartRuntime};'install-service'{Install};'remove-service'{Remove};'migrate-service'{MigrateService};setup{Setup};'production-repair'{ProductionRepair};'db-test'{DbTest};migrate{& npm run db:migrate;exit $LASTEXITCODE};'dependency-test'{DependencyTest};'dependency-install'{& npm ci;exit $LASTEXITCODE};port{SetPort};logs{Logs};health{$h=Health;if(-not$h){Fail 'Unreachable'};$h|ConvertTo-Json -Depth 6};'check-update'{CheckUpdate};update{Update};rollback{Rollback};version{Write-Host "Installed: $((Get-Content -Raw package.json|ConvertFrom-Json).version)";$h=Health;Write-Host "Running: $(if($h){$h.version}else{'unreachable'})"};doctor{Doctor};help{Write-Host 'Canonical commands: status uptime health version logs doctor port check-update start stop restart install-service remove-service update rollback help migrate-service setup production-repair db-test migrate dependency-test dependency-install'}}
